---
- hosts: your_target_servers
  become: yes
  tasks:
    - name: Stop and disable the app service
      systemd:
        name: app
        state: stopped
        enabled: no

    - name: Remove app service file
      file:
        path: "/etc/systemd/system/app.service"
        state: absent

    - name: Remove Java app directory
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Remove Nginx configuration file
      file:
        path: "/etc/nginx/nginx.conf"
        state: absent

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent

    - name: Remove Java package
      apt:
        name: openjdk-11-jre
        state: absent
