---
- hosts: your_target_servers
  become: yes
  vars_files:
    - all_vars.yml
  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ packages }}"
        state: present

    - name: Set apt cache time
      apt:
        name: apt
        update_cache: yes
        cache_valid_time: "{{ aptcachetime }}"

    - name: Create Java app directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy Java app file
      copy:
        src: "{{ app_file }}"
        dest: "{{ app_dir }}/{{ app_file | basename }}"

    - name: Create app service file from template
      template:
        src: app.service.j2
        dest: "/etc/systemd/system/app.service"
      notify: restart app service

    - name: Ensure app service is started and enabled
      systemd:
        name: app
        state: started
        enabled: yes

    - name: Create users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
      with_items: "{{ users }}"
      when: users is defined

    - name: Copy Nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx service

  handlers:
    - name: restart app service
      systemd:
        name: app
        state: restarted

    - name: restart nginx service
      systemd:
        name: nginx
        state: restarted
